### ISSUE TITLE
! When you delete target groups or venues that activities depend on, stuff gets messed up

### ISSUE THREAD

**Issue by clar-reese** [JNM-2T17/ActivityScheduler#6]
If ever we can tell whoever signs off on using this that we'll fix problems like this over the break or something because eh :/
<img width="1230" alt="screen shot 2016-08-23 at 9 54 20 pm" src="https://cloud.githubusercontent.com/assets/8152645/17894526/399781ee-697c-11e6-8897-96be85eb5bfa.png">

**Comment by ryanaustinf** [comment]
Blocked deleting
